### ISSUE TITLE
expanding strings instead of letters

### ISSUE THREAD

**Issue by aloispichler** [cohama/lexima.vim#135]
I tried the following rule
`call lexima#add_rule({'char': '\big(', 'input_after': '\big)', 'filetype': 'latex'})`,
which expands correctly, but before that only the letters \ - b - i - g - ) are visible, one after the another.
What did I wrong?

**Comment by cohama** [comment]
What you want is the following?

```
before | input | after
\big|  |  (    | \big(\big)
```

`char` will be used as lhs of `imap` such as `imap \big( \big(\big)<Left><Left><Left><Left>`.

You need to map only `(` and specify `at` to add context. A better rule is the follow.

```vim
call lexima#add_rule({'char': '(', 'at': '\\big\%#', 'input_after': '\big)', 'filetype': 'latex'})
```

FYI: Escape `\` in `at` clause because it is treated as `search` argument. For example `\sin` is treated as `SPACE + "in"`.

**Comment by cohama** [comment]
Good.
