### ISSUE TITLE
Mysterious errors when adding newline

### ISSUE THREAD

**Issue by smackesey** [cohama/lexima.vim#15]
In the following buffer (cursor indicated by "|" at the end of the last line), pressing return gives me a series of errors.

    ---
    id: vkegrjzo
    key: vimscript_vim-sneak.lib.vkegrjzo
    type:
    - library
    title: vim-sneak
    language: vimscript.pgl.bxsevhau
    github: justinmk/vim-sneak

    ---|

These are the errors:

    =<SNR>79_map_impl('
    E115: Missing quote: '
    E116: Invalid arguments for function <SNR>79_map_impl('
    E15: Invalid expression: <SNR>79_map_impl('

I am using lexima with no custom configuration.

**Comment by noahfrederick** [comment]
@smackesey Do you happen to also have https://github.com/tpope/vim-endwise installed? In my case, it seems to be a conflict with that plug-in, as the error goes away when I uninstall endwise.vim or when I load lexima.vim after endwise.vim instead of before.

Here's the output of `:verbose imap <CR>` when lexima.vim is loaded after endwise.vim (works fine):

    i  <CR>        * <C-R>=<SNR>31_map_impl('<CR>', '<CR>')<CR>
            Last set from ~/src/dots/vim/plugged/lexima.vim/autoload/lexima/insmode.vim

And when lexima.vim is loaded first (produces error):

    i  <CR>        & <C-R>=<SNR>24_map_impl('<CR>', '<CR>')<CR><SNR>36_DiscretionaryEnd
            Last set from ~/src/dots/vim/plugged/vim-endwise/plugin/endwise.vim

**Comment by smackesey** [comment]
Indeed I was using endwise and loading it before lexima. I changed the
order and now it works fine. Thanks for the pointer!

**Comment by noahfrederick** [comment]
No problem. I presume endwise is actually at fault here, though I haven't looked into it yet.

**Comment by cohama** [comment]
Do you have any problems yet?
I will close this issue soon.

**Comment by smackesey** [comment]
No problems since putting lexima before endwise.
