### ISSUE TITLE
Error (Undefined variable: v:t_number) while using the latest lexima version

### ISSUE THREAD

**Issue by installero** [cohama/lexima.vim#93]
Hello, my vim config looks like [this](https://github.com/installero/.vim).

I got this error while starting the vim from terminal.

```
Error detected while processing function <SNR>37_import[11]..<SNR>37__import:
line   18:
E605: Exception not caught: vital: fail to call ._vital_loaded(): vital: fail to
 call ._vital_loaded(): Vim(let):E121: Undefined variable: v:t_number from:^@ fr
om:^@function <SNR>37_import(...) Line:11 (~/.vim/plugged/lexima.vim/autoload/vi
tal/lexima.vim)^@function <SNR>37__import(...) Line:15 (~/.vim/plugged/lexima.vi
m/autoload/vital/lexima.vim)^@function <SNR>41__vital_loaded(...) Line:2 (~/.vim
/plugged/lexima.vim/autoload/vital/_lexima/Vim/Buffer.vim)^@function <SNR>37_imp
ort(...) Line:11 (~/.vim/plugged/lexima.vim/autoload/vital/lexima.vim)^@<SNR>37_
_import
```

After this lexima seems to work ok.

Can you please tell, what the problem could be?

**Comment by cohama** [comment]
Sorry for inconvenience. Latest vital.vim causes this problem in old Vim (<8.0).
I plan to fix this issue because support Vim version of lexima.vim is Vim7.4 (or higher)

Available workaround is
* Use Vim8 or newer neovim (I don't know which neovim version supports new vital.vim)
* Use old version lexima.vim (commit@ab74d24daf815c30de367c6e3518296eb9a84537 may be ok)

**Comment by installero** [comment]
Thanx, this setting in my vim-plug list of plugins helped!

```
Plug 'cohama/lexima.vim', { 'commit': 'ab74d24daf815c30de367c6e3518296eb9a84537' }
```
